apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: truenas-nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-test
  template:
    metadata:
      labels:
        app: nfs-test
    spec:
      containers:
      - name: test
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            echo "Pod $(hostname) started at $(date)" >> /data/test.log
            while true; do
              echo "$(date) - $(hostname) - Writing to NFS" >> /data/test.log
              cat /data/test.log
              sleep 10
            done
        volumeMounts:
        - name: nfs-volume
          mountPath: /data
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-test-pvc