# nfs-dynamic-test.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs  # Use your existing StorageClass
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-test
  template:
    metadata:
      labels:
        app: nfs-test
    spec:
      containers:
      - name: test
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            echo "Pod $(hostname) started at $(date)" | tee -a /data/test.log
            while true; do
              echo "$(date) - $(hostname) - NFS Test" | tee -a /data/test.log
              echo "=== Last 5 entries ==="
              tail -5 /data/test.log
              sleep 10
            done
        volumeMounts:
        - name: nfs-volume
          mountPath: /data
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-test-pvc