# nfs-test-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: YOUR_TRUENAS_IP
    path: /mnt/YOUR_POOL/YOUR_DATASET
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-test-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-test
  template:
    metadata:
      labels:
        app: nfs-test
    spec:
      containers:
      - name: test
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            echo "Pod $(hostname) started at $(date)" >> /data/test.log
            while true; do
              echo "$(date) - $(hostname) - Writing to NFS" >> /data/test.log
              cat /data/test.log
              sleep 10
            done
        volumeMounts:
        - name: nfs-volume
          mountPath: /data
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-test-pvc