apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.41.10
  share: /mnt/BigSpeed/rke-test
  mountOptions: "nfsvers=4.1"